### ISSUE TITLE
How to use other methods to complete NER tasks

### ISSUE THREAD

**Issue by luoqishuai** [ToluClassics/Notebooks#1]
You did the NER task using text-to-text.
So how do you do NER tasks using origin methods instead of text to text?  
For example, using BERT last layers "output embedding"/"token embedding" + Softmax.
I would appreciate your reply .

**Comment by ToluClassics** [comment]
Hello @luoqishuai , In Text2Text like T5, the classes for tokens are produced in a Generative Fashion but in a non-Text2Text fashion the model just generates a class for each token. So there's a final linear layer that produces a probability distribution over the classes (LOC, ORG, PER, e.t.c) for each token. In BERT, the Output Embeddings pass through an extra layer that maps them Od(Output dimension) to Cd(number of classes). You can also use a Conditional Random Field instead of the soft max.

Some people do this classification at a character level

**Comment by luoqishuai** [comment]
Thinks.
I will try to use "Encoder-Transformer- 11-FeedForward -Norm" layer's output to complete the NER task. 
Text2Text was also used to complete the NER. After all, this was mentioned in the paper.
